services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
#    volumes:
#        - redis_data:/data
#    command: [ "redis-server", "--save", "60", "1", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  backend-service:
    image: openjdk:17
    container_name: takenft_app
    volumes:
      - ./build/libs/takenft.jar:takenft.jar
      - ./.env:/.env
    command: ["java", "-jar", "takenft.jar"]
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always


volumes:
  pgdata:
