services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: takeNft
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
#    volumes:
#        - redis_data:/data
#    command: [ "redis-server", "--save", "60", "1", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
