services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
        - ./redis_data:/data
    command: [ "redis-server", "--save", "60", "1", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    image: openjdk:17
    container_name: app
    restart: always
    volumes:
      - ./build/libs/takenft.jar:/app/takenft.jar
      - ./.env:/.env
      - ./logs:/logs
    env_file:
      - .env
    command: ["java", "-jar", "/app/takenft.jar"]
    depends_on:
      - db
      - redis
      - rabbitmq
      - minio
    ports:
      - "8080:8080"
