server:
  port: 8080

spring:
  application:
    name: takeNft

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/takeNft
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672

  web:
    resources:
      add-mappings: true

      static-locations: classpath:/static/,classpath:/public/,file:uploads/

logging:
  level:
    root: INFO
    take_nft: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/take-nft.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
