server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: takeNft

  config:
    import: optional:file:.env[.properties]

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: ${REDIS_PORT}

  rabbitmq:
    host: rabbitmq
    port: ${RABBITMQ}

  web:
    resources:
      add-mappings: true

      static-locations: classpath:/static/,classpath:/public/,file:uploads/

logging:
  level:
    root: INFO
    take_nft: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/take-nft.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"