name: Deploy buy runner

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Stop backend container if running
        run: docker compose -f ./docker-compose.yml stop

      - name: remove app containers only
        run: |
          docker compose rm backend-service

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose
        run: docker compose up -d

