name: Deploy-job

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  hoba:
    runs-on: ubuntu-latest
    name: Deploy with rsync exclude and run Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with Exclude Patterns
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: 'root'
          server: 'takenft.ru'
          ssh_private_key: ${secrets.SSH_PRIVATE_KEY }
          local_path: './'
          remote_path: '/var/www/app'
          rsyncArgs: '--exclude=node_modules --exclude=.git --exclude=*.log'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Run Docker on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 'takenft.ru'
          username: 'root'
          key: ${secrets.SSH_PRIVATE_KEY}
          script: |
            cd /var/www/app
            docker compose -f ./docker-compose.yml stop
            docker compose rm backend-service
            ./gradlew bootJar
            docker compose up -d --build