name: Deploy-job

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  hobs:
    runs-on: ubuntu-latest
    name: Deploy and run Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file and run Docker on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 'takenft.ru'
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
            cd app/TakeNft/
            
            git pull origin master
            docker compose -f ./docker-compose.yml stop
            docker compose rm backend-service
            
            ./gradlew bootJar
            docker compose up -d --build