name: Deploy buy runner

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  hoba:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Stop backend container if running
        run: docker compose -f ./docker-compose.yml stop

      - name: remove app containers only
        run: |
          docker compose rm backend-service

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Show built JAR
        run: ls -lh build/libs

      - name: docker compose
        run: docker compose up -d

